### ISSUE TITLE
Ціна

### ISSUE THREAD

**Issue by nasapota** [nasapota/stelikievua#4]
Ціна - від 190грн.

**Comment by litoshko** [comment]
Було 2 ціни в 160: 
В цінах
![image](https://user-images.githubusercontent.com/7101847/92155589-4b74ad00-ee30-11ea-9332-5c611bcc5a16.png)
І в акціях:
![image](https://user-images.githubusercontent.com/7101847/92155654-62b39a80-ee30-11ea-8d42-6c734b09fade.png)
